/*
Copyright 2022 Max T.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	v1beta1 "github.com/upbound/provider-gcp/apis/compute/v1beta1"
	common "github.com/upbound/provider-gcp/config/common"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this ForwardingRule.
func (mg *ForwardingRule) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BackendService),
		Extract:      common.SelfLinkExtractor(),
		Reference:    mg.Spec.ForProvider.BackendServiceRef,
		Selector:     mg.Spec.ForProvider.BackendServiceSelector,
		To: reference.To{
			List:    &v1beta1.BackendServiceList{},
			Managed: &v1beta1.BackendService{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BackendService")
	}
	mg.Spec.ForProvider.BackendService = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BackendServiceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IPAddress),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.IPAddressRef,
		Selector:     mg.Spec.ForProvider.IPAddressSelector,
		To: reference.To{
			List:    &v1beta1.AddressList{},
			Managed: &v1beta1.Address{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.IPAddress")
	}
	mg.Spec.ForProvider.IPAddress = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.IPAddressRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Network),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.NetworkRef,
		Selector:     mg.Spec.ForProvider.NetworkSelector,
		To: reference.To{
			List:    &v1beta1.NetworkList{},
			Managed: &v1beta1.Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Network")
	}
	mg.Spec.ForProvider.Network = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetworkRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Subnetwork),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.SubnetworkRef,
		Selector:     mg.Spec.ForProvider.SubnetworkSelector,
		To: reference.To{
			List:    &v1beta1.SubnetworkList{},
			Managed: &v1beta1.Subnetwork{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Subnetwork")
	}
	mg.Spec.ForProvider.Subnetwork = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubnetworkRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Target),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.TargetRef,
		Selector:     mg.Spec.ForProvider.TargetSelector,
		To: reference.To{
			List:    &RegionTargetTCPProxyList{},
			Managed: &RegionTargetTCPProxy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Target")
	}
	mg.Spec.ForProvider.Target = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.TargetRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this RegionTargetTCPProxy.
func (mg *RegionTargetTCPProxy) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BackendService),
		Extract:      common.SelfLinkExtractor(),
		Reference:    mg.Spec.ForProvider.BackendServiceRef,
		Selector:     mg.Spec.ForProvider.BackendServiceSelector,
		To: reference.To{
			List:    &v1beta1.BackendServiceList{},
			Managed: &v1beta1.BackendService{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BackendService")
	}
	mg.Spec.ForProvider.BackendService = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BackendServiceRef = rsp.ResolvedReference

	return nil
}
