apiVersion: compute.gcp-beta.max4t.xyz/v1beta1
kind: ForwardingRule
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/forwardingrule
  labels:
    testing.upbound.io/example-name: google_compute_forwarding_rule
  name: google-compute-forwarding-rule
spec:
  forProvider:
    ipProtocol: TCP
    loadBalancingScheme: INTERNAL_MANAGED
    networkSelector:
      matchLabels:
        testing.upbound.io/example-name: ilb_network
    networkTier: PREMIUM
    portRange: "80"
    provider: ${google-beta}
    region: europe-west1
    subnetworkSelector:
      matchLabels:
        testing.upbound.io/example-name: ilb_subnet
    targetSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

